#!/usr/bin/env bash
# Mintlify OpenAPI is generated by Speakeasy CLI (speakeasy pull), committed under openapi/.
set -euo pipefail

DOCS_JSON="${1:-docs.json}"
OPENAPI_PATH="$(jq -r '.navigation.tabs[] | select(.tab == "API reference") | .openapi' "$DOCS_JSON")"

if [ "$OPENAPI_PATH" != "/openapi/openapi.yaml" ] && [ "$OPENAPI_PATH" != "openapi/openapi.yaml" ]; then
  echo "docs.json must point at Speakeasy-pulled file /openapi/openapi.yaml, got: ${OPENAPI_PATH}" >&2
  exit 1
fi

REL="${OPENAPI_PATH#/}"
if [ ! -f "$REL" ]; then
  if [ "${CI_VALIDATE_DOCS_JSON_ONLY:-}" = "true" ]; then
    echo "docs.json path OK; ${REL} will be filled by speakeasy pull on deploy"
    exit 0
  fi
  echo "Missing ${REL} — run speakeasy pull --spec=galya-api-with-code-samples (CI does this before deploy)" >&2
  exit 1
fi

echo "Mintlify API reference uses Speakeasy-generated ${REL}"
